#index:
# path: /
# controller: App\Controller\DefaultController::index
fos_user:
  resource: "@FOSUserBundle/Resources/config/routing/all.xml"
#front_homepage:
# path: /home
# defaults: { _controller: BackBundleController:Default:index }

ListCollaborateurs:
  path: /ListCollaborateurs
  defaults: { _controller: AppBundle:Default:ListCollaborateurs }
